# Generated by Django 2.1.5 on 2020-01-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200130_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
